import type { Metadata } from "next";
// import {Providers} from "./providers";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ 
  weight: ['400', '700'],
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Home | My Portfolio",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  pageTitle: string;
}
export default function RootLayout({ children, pageTitle }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-[#222222] min-h-screen `}>
        <Header />
        
        {children}
        <Footer />
      </body>
    </html>
  );
}
